config/routes.rb
Rails.application.routes.draw do
  get 'about/index'

  get 'welcome/index'
  resources :blog
  post 'documents/upload'

  resources :documents
  get 'documents/:id' => 'documents#show'

  root 'welcome#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  validates :title, presence: true
  validates :body , presence: true

  has_many :documents, as: :uploadable

  accepts_nested_attributes_for :documents

  def documents_attributes=(document_ids)
    self.documents = Document.where('id in (?)', document_ids)
  end
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :uploadable, polymorphic: true

  enum purpose: [:BLOG_ATTACHMENT]
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
    @links = @blog.links
  end

  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to @blog
    else
      render 'new'
    end
  end

  def blog_params
    params.require(:blog).permit(:title, :body, :links, :documents_attributes, documents_attributes: [])
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  def upload
    document = create_document(upload_params[:file])
    render json: { document_id: document.id, file_name: document.file_name, file_size: "#{upload_params[:file].size / 1000} mb" }
  end

  def show
    document = Document.find_by(id: params[:id])
    send_data(document.file, filename: document.file_name)
  end

  def destroy
    Document.find_by(id: params[:id]).try(:destroy)
    render json: true
  end

  private

  def create_document(file)
    Document.create(
        file: file.read,
        file_name: file.original_filename,
        mime_type: file.content_type,
        purpose: Document.purposes[:BLOG_ATTACHMENT]
    )
  end

  def upload_params
    params.permit(:file)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.slim
div.page-header
  script
  h1 About
p This is a insecure Blog application
p
  | Authors : Prasanna K  & Alex

app/views/blog/_file_upload.html.slim
script id="fileUploadProgressTemplate" type="text/x-jquery-tmpl"
  div.list-group-item
    div.progress.progress-striped.active
      div.progress-bar.progress-bar-info style="width: 0%;"

script id="fileUploadItemTemplate" type="text/x-jquery-tmpl"
  div class="uploaded_item list-group-item"
    input type='hidden' name='blog[documents_attributes][]' value='${document_id}'
    button type="button" name="fileUploadCloseButton" value='${document_id}' class="close" &times;
    span.glyphicon.glyphicon-file name='fileInfo'
    /|  ${file_name} (${file_size})

div#fileUpload.fileUpload.btn.btn-default
  span.glyphicon.glyphicon-upload
  |  Upload File
= form.file_field(:uploadFile, id: :uploadFile, style: 'display: none')

br: br

p id="fileUploadError" class="text-danger hide"
div class="list-group" id="uploadedFiles"
  span Files Uploaded:

app/views/blog/index.html.slim
div.page-header
  h1 Exciting Blogs of Insecure
div
  - unless @blogs.empty?
    table
      - @blogs.each do |blog|
        tr: td
            li
              = link_to blog.title, blog_path(blog.id)

br
div.alert.alert-info
    strong Total Blogs: #{@blogs.count}

a href="#" class="btn btn-primary" role="button" New Blog

app/views/blog/new.html.slim
div.page-header
  h1 Write your new Blog !!

div.new_blog
  = form_for(:blog, {url: '/blog'}) do |f|
    table class='table table-hover table-responsive'
      thead
        tr
          th
          th

      tr
        td.col-md-3 Title
        td
          = f.text_field :title, placeholder: 'Title', class: 'form-control', required: 'required'
      tr
        td.col-md-3 Body
        td
          = f.text_area :body, placeholder: 'Body', class: 'form-control', required: 'required'
      tr
        td.col-md-3 Links
        td
          = f.text_area(:links, placeholder: 'Links', class: 'form-control')
      tr
        td.col-md-3 Attachments
        td
          = render :partial => 'blog/file_upload', locals: { form: f }
      tr
        td.col-md-3
        td
          button type="submit" class="btn btn-primary": span class="glyphicon" Submit

app/views/blog/show.html.slim
div.page-header
  h1 =@blog.title
div
  =@blog.body

- if @blog.links.present?
  div
    br
    br
    b Links:
    br
    br
    = link_to @links, target: "_blank" do
      -@links

- if @blog.documents.present?
  br
  div
    strong Attachments:
    br
    - @blog.documents.each do |document|
      li
        = link_to document.file_name, document_path(document.id), target: '_blank'

app/views/layouts/_navbar.html.slim
div class="navbar navbar-inverse navbar-static-top" role="navigation"
  div class="container"
    div class="navbar-header"
      button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"
        span class="sr-only" Toggle navigation
        span class="icon-bar"
        span class="icon-bar"
        span class="icon-bar"
      a.navbar-brand Insecure Blog

    div class="navbar-collapse collapse"
      ul class="nav navbar-nav"
        - [{path: root_path, label: 'Home'}, {path: blog_index_path, label: 'Blogs'}, {path: new_blog_path, label: 'New Blog'}, {path: about_index_path, label: 'About'}].each do |path_info|
          li class=(path_info[:path] == request.env['PATH_INFO'] ? 'active' : '') : a href="#{path_info[:path]}" #{path_info[:label]}

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title Insecure Blog

    = stylesheet_link_tag 'application', media: :all
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    = render :partial => 'layouts/navbar'
    div.container
      == yield

app/views/welcome/index.html.slim
div.page-header
  h1 Welcome
p This is a Test System still in Development. This is insecure by design. It has DOM XSS at the moment. Please use with care.
javascript:
  add()